short circuits, how do they work

diff --git a/files/default/opennms-26-dot-two-dot-some b/files/default/opennms-26-dot-two-dot-some
--- a/files/default/opennms-26-dot-two-dot-some
+++ b/files/default/opennms-26-dot-two-dot-some
@@ -1,21 +1,21 @@
 #!/bin/bash
 #
 # chkconfig:   345 99 01
-# description: Starts and stops the ${install.package.description} network management \
+# description: Starts and stops the OpenNMS network management \
 #              poller and backend processes
 # processname: opennms
-# pidfile:     ${install.pid.file}
+# pidfile:     /opt/opennms/logs/opennms.pid
 #
 ### BEGIN INIT INFO
 # Provides:          opennms
 # Required-Start:    $local_fs $network
-# Should-Start:      $time $named ypbind ${install.postgresql.service}
+# Should-Start:      $time $named ypbind postgresql
 # Required-Stop:     $local_fs $network
 # Should-Stop:       $time $named ypbind
 # Default-Start:     3 5
 # Default-Stop:      0 1 2 6
-# Short-Description: ${install.package.description} daemon for network monitoring
-# Description:       ${install.package.description} daemon for network monitoring
+# Short-Description: OpenNMS daemon for network monitoring
+# Description:       OpenNMS daemon for network monitoring
 ### END INIT INFO
 #
 #  $Id$
@@ -38,17 +38,17 @@
 
 # Home directory for OpenNMS.
 # shellcheck disable=SC2154
-OPENNMS_HOME="${install.dir}"
+OPENNMS_HOME="/opt/opennms"
 
 # PID file for OpenNMS.
-OPENNMS_PIDFILE="${install.pid.file}"
+OPENNMS_PIDFILE="/opt/opennms/logs/opennms.pid"
 
 # Log directory for OpenNMS
-LOG_DIRECTORY="${install.logs.dir}"
+LOG_DIRECTORY="/opt/opennms/logs"
 
 # Directory where init functions are likely stored (we also check a few other
 # directories, just in case)
-INITDIR="${install.init.dir}"
+INITDIR="/etc/init.d"
 
 # Where to redirect "start" output.
 REDIRECT="$LOG_DIRECTORY/output.log"
@@ -154,11 +154,11 @@ Usage: $0 [-f] [-n] [-t] [-p] [-o] [-c timeout] [-v] [-Q] <command> [<service>]
       -o  Enable OProfile profiling
       -c  Controller HTTP connection timeout in seconds.
       -v  Verbose mode.  When used with the "status" command, gives the
-          results for all ${install.package.description} services.
+          results for all OpenNMS services.
           When used with "start", enables some verbose debugging, such
           as details on garbage collection.
-      -Q  Quick mode.  Don't wait for ${install.package.description} to start up.
-          Useful if you want to watch the logs while ${install.package.description} starts up
+      -Q  Quick mode.  Don't wait for OpenNMS to start up.
+          Useful if you want to watch the logs while OpenNMS starts up
           without wanting to open another terminal window.
 
 END
@@ -279,7 +279,7 @@ The format of the original files may have changed since
 you modified them before installing a new version.
 Please double-check that your configuration files are
 up-to-date and delete any leftover .$EXTENSION files or
-${install.package.description} will not start.
+OpenNMS will not start.
 
 END
 				case "$COMMAND" in
@@ -312,7 +312,7 @@ checkLogDir(){
 checkConfigured() {
 	if [ ! -f "$OPENNMS_HOME/etc/configured" ]; then
 		cat <<END >&2
-$0: ${install.package.description} not configured.
+$0: OpenNMS not configured.
 $OPENNMS_HOME/etc/configured does not exist.
 
 You need to run the installer to set up the database.  In most
@@ -373,13 +373,13 @@ doStart(){
 	status=$?
 	case $status in
 		0)
-			echo "${install.package.description} is already running." >&2
+			echo "OpenNMS is already running." >&2
 			return 0
 			;;
 
 		160)
-			echo "${install.package.description} is partially running." >&2
-			echo "If you have just attempted starting ${install.package.description}, please try again in a few" >&2
+			echo "OpenNMS is partially running." >&2
+			echo "If you have just attempted starting OpenNMS, please try again in a few" >&2
 			echo "moments, otherwise, at least one service probably had issues starting." >&2
 			echo "Check your logs in $LOG_DIRECTORY for errors." >&2
 			return 1
@@ -398,7 +398,7 @@ doStart(){
 
 
 	if [ "$NOEXECUTE" -eq 0 ] && ! "${JAVA_CMD[@]}" "-Dopennms.home=$OPENNMS_HOME" -jar "$BOOTSTRAP" check; then
-		echo "${install.package.description} was unable to connect to the 'opennms' database configured in opennms-datasources.xml." >&2
+		echo "OpenNMS was unable to connect to the 'opennms' database configured in opennms-datasources.xml." >&2
 		return 1
 	fi
 
@@ -485,14 +485,14 @@ doStart(){
 		if isRunning "$(getPid)"; then
 			true		# Java process is still running... don't do anything
 		else
-			echo "Started ${install.package.description}, but it stopped running: for details see $REDIRECT" >&2
+			echo "Started OpenNMS, but it stopped running: for details see $REDIRECT" >&2
 			return 1
 		fi
 		sleep $STATUS_WAIT
 		((STATUS_ATTEMPTS++))
 	done
 
-	echo "Started ${install.package.description}, but it has not finished starting up" >&2
+	echo "Started OpenNMS, but it has not finished starting up" >&2
 	return 1
 }
 
@@ -513,7 +513,7 @@ doPause(){
 		fi
 		runCmd "${JAVA_CMD[@]}" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}"
 	else
-		echo "${install.package.description} is not running." >&2
+		echo "OpenNMS is not running." >&2
 	fi
 }
 
@@ -534,7 +534,7 @@ doResume(){
 		fi
 		runCmd "${JAVA_CMD[@]}" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}"
 	else
-		echo "${install.package.description} is not running." >&2
+		echo "OpenNMS is not running." >&2
 	fi
 }
 
@@ -544,7 +544,7 @@ doCheck() {
 		exit 0
 	fi
 
-	echo "${install.package.description} is not running... Restarting" >&2
+	echo "OpenNMS is not running... Restarting" >&2
 	"$OPENNMS_HOME/bin/opennms" start
 
 	exit 0
@@ -553,13 +553,13 @@ doCheck() {
 doStop() {
 	doStatus "$@"
 	if [ "$?" -eq 3 ]; then
-		(sleep 1; echo "Trying to stop ${install.package.description} but it's already stopped." >&2)
+		(sleep 1; echo "Trying to stop OpenNMS but it's already stopped." >&2)
 		return 0   # LSB says: stopping when stopped is successful
 	fi
 
 	PID="$(getPid)"
 	if [ "$PID" -gt 0 ]; then
-		echo "=== ${install.package.description} Complimentary Thread Dump ===" >> "$REDIRECT"
+		echo "=== OpenNMS Complimentary Thread Dump ===" >> "$REDIRECT"
 		kill -3 "$PID" >> "$REDIRECT" 2>&1
 	else
 		echo "=== WARNING: Unable to Perform Complimentary Thread Dump ===" >> "$REDIRECT"
@@ -902,7 +902,7 @@ fi
 
 case "$COMMAND" in
 	start|spawn)
-		$opennms_echo "Starting ${install.package.description}: \c"
+		$opennms_echo "Starting OpenNMS: \c"
 
 		doStart "$@"
 		__ret="$?"
@@ -931,7 +931,7 @@ case "$COMMAND" in
 		;;
 
 	stop)
-		$opennms_echo "Stopping ${install.package.description}: \c"
+		$opennms_echo "Stopping OpenNMS: \c"
 
 		doStop "$@"
 		__ret="$?"
@@ -985,7 +985,7 @@ case "$COMMAND" in
 
 	status)
 		if [ -f /etc/SuSE-release ]; then
-			$opennms_echo "Checking for ${install.package.description}: \c"
+			$opennms_echo "Checking for OpenNMS: \c"
 			if [ "$VERBOSE" -gt 0 ]; then
 				echo ""
 			fi
@@ -1013,6 +1013,7 @@ case "$COMMAND" in
 					echo "Unknown return code from doStatus: $__ret" >&2
 			esac
 		fi
+                exit "$__ret"
 		;;
 
 	configtest)
